# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    single_trx:
      playwright_script: "test:playwright-single-trx"
    multi_trx:
      playwright_script: "test:playwright-multi-trx"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# This task must not throw any error, .i.e not exit with 1. Otherwise, `PublishTestResults` will not run.
- script: |
    npm run $(playwright_script)
  displayName: 'npm test'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/playwright-test-reports/*.trx'
    testResultsFormat: 'VSTest'
    failTaskOnFailedTests: true
    mergeTestResults: true
